# Generated by Django 3.1.7 on 2021-04-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_y_Apellido', models.CharField(max_length=50, null=True)),
                ('Telefono', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('Mensaje', models.CharField(max_length=50, null=True)),
                ('Atendido', models.BooleanField(default=False, verbose_name='Atendido')),
            ],
        ),
    ]
