# Generated by Django 3.2 on 2021-04-15 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkevin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modalidad', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Mensaje',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Nombre_y_Apellido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='modalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appkevin.modalidade'),
        ),
    ]
